project:
  type: website
  output-dir: ../docs

website:
  title: "webpage"
  navbar:
  background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Resume
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

