project:
  type: website
  output-dir: ../docs

website:
  title: "webpage"
  navbar:
    background: '#0fbfcf'
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Resume
        
format:
  html:
    theme:
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

